### ISSUE TITLE
feat: improve reliability of QR Code Service in PR bot

### ISSUE THREAD

**Issue by venkatamutyala** [GlueOps/pull-request-bot#11]
Currently PR bot uses a third party QR code service: https://github.com/GlueOps/pull-request-bot/blob/main/main.py#L220

Example:

`curl "https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=https://yahoo.com"`

or just [click here](https://api.qrserver.com/v1/create-qr-code/?size=150x150&data=https://yahoo.com)

We want to remove this dependency on a third party because if they go down then the PR bot feature of the platform is at risk of going offline as well. 

Requirements:
- Replace the dependency on qr code server. Either add the QR code generation into Pull Request bot directly or keep it as a separate service that gets deployed into the clients cluster.
- If it's a new service:
> add authentication to the endpoint.
> Update PR bot to use the API Key for that endpoint
> Don't add an ingress object as it should be an internal only service.

**Comment by Mbaoma** [comment]
Hi @venkatamutyala, kindly check out my solution on branch qr-code-generator: https://github.com/GlueOps/pull-request-bot/tree/qr-code-generator
